// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (insert_time_milli)
VALUES ($1)
RETURNING id, insert_time_milli
`

func (q *Queries) CreateUser(ctx context.Context, insertTimeMilli int64) (User, error) {
	row := q.db.QueryRow(ctx, createUser, insertTimeMilli)
	var i User
	err := row.Scan(&i.ID, &i.InsertTimeMilli)
	return i, err
}
